#!/bin/bash
# Author: Ninos Boulous
# Created date: 9/18/19
# GitHub source -- https://github.com/ninob116/Scripts/Bound Mac's Last Changed AD Password
#------------------------------------------------------------------------------------------

CurrentUser=$(stat -f%Su /dev/console)
Domain=`echo show com.apple.opendirectoryd.ActiveDirectory | scutil | grep DomainNameFlat | awk '{print $3}'`
MSLastPWD=`dscl "/Active Directory/$Domain/All Domains" -read /Users/$CurrentUser | grep -i SMBPasswordLastSet | cut -d ' ' -f 2 | sed q`
pwdLastSet="$MSLastPWD"
pwdLastSet_EPOCH=`/bin/echo $((($pwdLastSet/10000000)-11644473600))`
date -r $pwdLastSet_EPOCH "+%m/%d/%Y %r"
